config/routes.rb
Rails.application.routes.draw do
  
  # Application root
  root 'application#index'
  
  devise_for :users
  
  resources :products, param: :product_id do
    collection do
      get 'my_products'
      get 'bids'
    end
    member do
      post 'back'
    end
  end
  
  resources :sellers do
    collection do
      get 'bid'
      get 'sold'
      post 'start_bid'
      get 'stop_bid'
    end
  end
  
  resources :buyers do
    collection do
      get 'search'
      get 'bought'
      post 'search_products'
      get 'ongoing_auctions'
      get 'my_bids'
      get 'place_new_bid'
      post 'place_bid'
      get 'revoke_bid'
    end
  end
  
  resources :categories, param: :category_id do
    member do 
        post 'back'
    end
  end
  
  get 'bids/:bid_id', to: 'bids#show'
  post '/bids/:bid_id', to: 'bids#show'
  get 'users/searchproductsunderbid', to: 'users#search_products_under_bid', as: :search_products
  get 'buyers/productsunderbid', to: 'buyers#get_products_under_bid'
  
  resources :bids, param: :bid_id
  resources :products_under_bids, param: :product_bid_id
  
end

app/controllers/buyer_controller.rb
class BuyerController < ApplicationController
    
    def get_products_under_bid
        @products_under_bid = ProductsUnderBid.get_products_under_bid
        
        respond_to do |format|
            format.html { redirect_to @products_under_bid, notice: 'Products under bid was successfully created.' }
            format.json { render json: @products_under_bid }
        end
    end
    
end

app/controllers/buyers_controller.rb
class BuyersController < UsersController
    before_action :authenticate_user!, only: [ :bought, :my_bids, :place_new_bid, :place_bid, :revoke_bid ]
    
    def show
        @matching_products = ProductsUnderBid.search_products_under_bid(name: $search_name, category_id: $search_category, 
                                                                        location_id: $search_location_id, highest_bid: $search_highest_bid)
        @matching_products = @matching_products.paginate(:page => params[:page],:per_page => 10)
        get_already_placed_bids(@matching_products)
    end
    
    def bought
        @products = Product.where(:user_id => current_user.id).joins('INNER JOIN products_under_bids ON products.product_id = products_under_bids.product_id').where('products_under_bids.sell_status' => true)
    end
    
    def search_products
        $search_name = params[:search][:name]
        $search_category = params[:search][:category_id].to_i
        $search_location_id = params[:search][:location_id].to_i
        $search_highest_bid = params[:search][:highest_bid].to_f
        @matching_products = ProductsUnderBid.search_products_under_bid(name: $search_name, category_id: $search_category, 
                                                                        location_id: $search_location_id, highest_bid: $search_highest_bid)
        @matching_products = @matching_products.paginate(:page => params[:page],:per_page => 10)
        get_already_placed_bids(@matching_products)
    end
    
    def ongoing_auctions
        @products_under_bid = ProductsUnderBid.get_products_under_bid
        @products_under_bid = @products_under_bid.paginate(:page => params[:page],:per_page => 10)
        get_already_placed_bids(@products_under_bid)
    end
    
    def my_bids
        @my_bids = Product.select("*").joins("INNER JOIN bids ON bids.product_id = products.product_id
                                    INNER JOIN products_under_bids ON products_under_bids.product_id = products.product_id")
                                    .where('bids.user_id' => current_user.id, 'bids.bid_active' => true)
    end
    
    def place_new_bid
        @product_id = params[:product_id]
        @highest_bid = params[:highest_bid]
    end
    
    def place_bid
        product_id = params[:bid][:product_id].to_i
        bid_amount = params[:bid][:bid_amount].to_f
        Bid.place_bid(product_id, current_user.id, bid_amount)
        redirect_to :action => 'ongoing_auctions' and return
    end
    
    def revoke_bid
        product_id = params[:product_id].to_i
        Bid.revoke_bid(product_id, current_user.id)
        redirect_to :action => 'ongoing_auctions' and return
    end
    
    private
    
    def get_already_placed_bids(products)
        @already_placed_bid = []
        products.each do |product|
            if !current_user.nil?
                placed_bid = Bid.where('product_id' => product.product_id, "user_id" => current_user.id, "bid_active" => true)
                if !placed_bid.blank?
                    @already_placed_bid << placed_bid.first.bid_amount
                else
                    @already_placed_bid << 0
                end
            else
                @already_placed_bid << 0
            end
        end    
    end
end

app/helpers/buyer_helper.rb
module BuyerHelper
end

app/views/buyers/_form.html.erb
<div class="col-md-5">
    <div class="panel panel-primary">
        <div class="panel-heading"><%= action %></div>
        <div class="panel-body">
 
            <%= form_for :search, url: { action: "search_products" } do |f| %>
                
                <div class="field">
                    <%= f.label :name %>
                        <%= f.text_field :name %>
                </div>
                
                <div class="field">
                    <%= f.label :category_id %>
                        <%= f.select :category_id, [""] + categories.map { |c| [c.name, c.category_id] } %>
                </div>

                <div class="field">
                    <%= f.label :location %>
                        <%= f.select :location_id, @locations.each_with_index.map { |l, l_id| [l, l_id] } %>
                </div>
                
                <div class="field">
                    <%= f.label :highest_bid %>
                        <%= f.text_field :highest_bid %>
                </div>

                <div class="actions">
                    <%= f.submit action, class: "btn btn-success" %>
                </div>
            <% end %>
        </div>
</div>

app/views/buyers/_show_products.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading"><%= action %></div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Category</th>
            <th>Image</th>
            <th>Location</th>
            <th>Your bid/Highest bid</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% products.each_with_index do |product, product_index| %>
            <tr>
              <td>
                <%= link_to product.name, bids_products_path(:product_id => product.product_id) %>
              </td>
              <td>
                <%= Category.find(product.category_id).name %>
              </td>
              <td>
                <%= link_to image_tag(product.image.url(:thumb), :class => "product")%>
              </td>
              <td>
                <%= @locations[product.location_id] %>
              </td>
              <td>
                <%= @already_placed_bid.present? ? @already_placed_bid[product_index] : product.bid_amount %>/<%= product.maximum_bidding_price %>
              </td>
              <td>
                <%= link_to 'Show', product %>
              </td>
              <td>
                <%= link_to 'Place Bid', place_new_bid_buyers_path(:product_id => product.product_id, :highest_bid => product.maximum_bidding_price) %>
              </td>
              <td>
                <%= link_to 'Revoke Bid', revoke_bid_buyers_path(:product_id => product.product_id) %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <div id="paginate">
        <%= will_paginate products, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/buyers/_show_products_ongoing_auctions.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading"><%= action %></div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Category</th>
            <th>Location</th>
            <th>Your bid/Highest bid</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% products.each_with_index do |product, product_index| %>
            <tr>
              <td>
                <%= link_to product.name, bids_products_path(:product_id => product.product_id) %>
              </td>
              <td>
                <%= Category.find(product.category_id).name %>
              </td>
              <td>
                <%= @locations[product.location_id] %>
              </td>
              <td>
                <%= @already_placed_bid.present? ? @already_placed_bid[product_index] : product.bid_amount %>/<%= product.maximum_bidding_price %>
              </td>
              <td>
                <%= link_to 'Show', product.becomes(Product) %>
              </td>
              <td>
                <%= link_to 'Place Bid', place_new_bid_buyers_path(:product_id => product.product_id, :highest_bid => product.maximum_bidding_price) %>
              </td>
              <td>
                <%= link_to 'Revoke Bid', revoke_bid_buyers_path(:product_id => product.product_id) %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <div id="paginate">
        <%= will_paginate products, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/buyers/bought.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading">Products</div>
    <div class="panel-body">
      <% cache(cache_key_for_products_table(@products)) do %>
      <table class="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Category</th>
            <th>Image</th>
            <th>Date added</th>
            <th>Location</th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <% cache(cache_key_for_products(product)) do %>
            <tr>
              <td>
                <%= product.name %>
              </td>
              <td>
                <%= Category.find(product.category_id).name %>
              </td>
              <td>
                <%= link_to image_tag product.image.url(:thumb), :class => "product" %>
              </td>
              <td>
                <%= product.date_added %>
              </td>
              <td>
                <%= @locations[product.location_id] %>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <% end %>
      <div id="paginate">
        <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/buyers/my_bids.html.erb
<%= render partial: "show_products", locals: { products: @my_bids, action: 'My Bids' } %>

app/views/buyers/ongoing_auctions.html.erb
<%= render partial: "show_products_ongoing_auctions", locals: { products: @products_under_bid, action: 'Ongoing Auctions' } %>

app/views/buyers/place_new_bid.html.erb
<div class="col-md-5">
    <div class="panel panel-primary">
        <div class="panel-heading">Place New Bid</div>
        <div class="panel-body">
 
            <%= form_for :bid, url: { action: "place_bid" } do |f| %>
            
                <div class="field">
                    <%= f.label :product_id %>
                        <%= f.text_field :product_id, :value => @product_id, :readonly => true %>
                </div>
                
                <div class="field">
                    <%= f.label :your_bid %>
                        <%= f.text_field :bid_amount, :value => @highest_bid %>
                </div>

                <div class="actions">
                    <%= f.submit "Place bid", class: "btn btn-success" %>
                </div>
            <% end %>
        </div>    
    </div>
</div>

app/views/buyers/search.html.erb
<%= render 'form', product: :search_product, categories: Category.all, action: 'Search Products' %>

app/views/buyers/search_product.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading">Products</div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Category</th>
            <th>Name</th>
            <th>Date added</th>
            <th>Location</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @matching_products.each do |product| %>
            <tr>
              <td>
                <%= Category.find(product.category_id).name %>
              </td>
              <td>
                <%= product.name %>
              </td>
              <td>
                <%= product.date_added %>
              </td>
              <td>
                <%= product.location %>
              </td>
              <td>
                <%= link_to 'Show', product %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/buyers/search_products.html.erb
<%= render partial: "show_products", locals: { products: @matching_products, action: 'Search Products' } %>

app/views/buyers/show.html.erb
<%= render partial: "show_products", locals: { products: @matching_products, action: 'Search Products' } %>