config/routes.rb
Rails.application.routes.draw do
  
  # Application root
  root 'application#index'
  
  devise_for :users
  
  resources :products, param: :product_id do
    collection do
      get 'my_products'
      get 'bids'
    end
    member do
      post 'back'
    end
  end
  
  resources :sellers do
    collection do
      get 'bid'
      get 'sold'
      post 'start_bid'
      get 'stop_bid'
    end
  end
  
  resources :buyers do
    collection do
      get 'search'
      get 'bought'
      post 'search_products'
      get 'ongoing_auctions'
      get 'my_bids'
      get 'place_new_bid'
      post 'place_bid'
      get 'revoke_bid'
    end
  end
  
  resources :categories, param: :category_id do
    member do 
        post 'back'
    end
  end
  
  get 'bids/:bid_id', to: 'bids#show'
  post '/bids/:bid_id', to: 'bids#show'
  get 'users/searchproductsunderbid', to: 'users#search_products_under_bid', as: :search_products
  get 'buyers/productsunderbid', to: 'buyers#get_products_under_bid'
  
  resources :bids, param: :bid_id
  resources :products_under_bids, param: :product_bid_id
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :random_latest_products
  protect_from_forgery with: :exception
  
  CACHE = Dalli::Client.new("biddingsystem.dgkfha.0001.usw2.cache.amazonaws.com:11211", { :expires_in => 1.day, :compress => true })
  
  def initialize
    
    super
    @locations = ["", "Alabama", "Alaska", "Arizona", "Arkansas", 
                    "California", "Colorado", "Connecticut", "Delaware",
                    "District of Columbia", "Florida", "Georgia", "Hawaii",
                    "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky",
                    "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan",
                    "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska",
                    "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York",
                    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
                    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
                    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
                    "West Virginia", "Wisconsin", "Wyoming"]
  end
  
  def random_latest_products
    @latest_products = Product.where(product_id: Product.last(10).pluck(:product_id).sample(3))
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Extend form_for to emit Bootstrap form code
    # http://stackoverflow.com/questions/18840947/how-to-get-class-form-control-in-input-fields-by-default-rails-form-helper
    
    module BootstrapExtension
    	FORM_CONTROL_CLASS = "form-control"
    
    	# Override the 'text_field' method defined in FormHelper
    	# https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_tag_helper.rb
    	
    	def text_field(name, value = nil, options = {})
    		class_name = options[:class]
    		if class_name.nil?
    			# Add 'form-control' as the only class if no class was provided
    			options[:class] = FORM_CONTROL_CLASS
    		else
    			# Add 'form-control' to the class if it doesn't already exist
    			options[:class] << " #{FORM_CONTROL_CLASS}" if
    			" #{class_name} ".index(" #{FORM_CONTROL_CLASS} ").nil?
    		end
    
    		# Call the original 'text_field' method to do the real work
    		super
    	end
    	
    	# Override the 'select' method defined in FormOptionsHelper
    	# https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_options_helper.rb
    	
    	def select(object, method, choices = nil, options = {}, html_options = {}, &block)
    		class_name = options[:class]
    		if class_name.nil?
    			# Add 'form-control' as the only class if no class was provided
    			html_options[:class] = FORM_CONTROL_CLASS
    		else
    			# Add 'form-control' to the class if it doesn't already exist
    			html_options[:class] << " #{FORM_CONTROL_CLASS}" if
    			" #{class_name} ".index(" #{FORM_CONTROL_CLASS} ").nil?
    		end
    
    		# Call the original 'select' method to do the real work
    		super
    	end
    end
    
    # Add the modified method to ApplicationHelper
    include BootstrapExtension
  
end

app/views/application/_current_products.html.erb
<div class="col-md-9">

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="https://placehold.it/320x150" alt="">
            <div class="caption">
                <h4 class="pull-right">$24.99</h4>
                <h4><a href="#">First Product</a>
                </h4>
                <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
            </div>
            <div class="ratings">
                <p class="pull-right">15 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                </p>
            </div>
            <div class="span7 text-center"><h4><a href="#">Bid your price</a></h4></div>
        </div>
    </div>

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="https://placehold.it/320x150" alt="">
            <div class="caption">
                <h4 class="pull-right">$64.99</h4>
                <h4><a href="#">Second Product</a>
                </h4>
                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="ratings">
                <p class="pull-right">12 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                </p>
            </div>
            <div class="span7 text-center"><h4><a href="#">Bid your price</a></h4></div>
        </div>
    </div>

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="https://placehold.it/320x150" alt="">
            <div class="caption">
                <h4 class="pull-right">$74.99</h4>
                <h4><a href="#">Third Product</a>
                </h4>
                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="ratings">
                <p class="pull-right">31 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                </p>
            </div>
            <div class="span7 text-center"><h4><a href="#">Bid your price</a></h4></div>
        </div>
    </div>
    
</div>

app/views/application/_footer.html.erb
 <div class="container">

    <hr/>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>CS291@UCSB 2016</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

app/views/application/_head.html.erb
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <title>Online Bidding System</title>

    <%= csrf_meta_tags %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- SmartMenus jQuery init -->
    <script type="text/javascript">
        $(function() {
            $('#main-menu').smartmenus({
                subMenusSubOffsetX: 1,
                subMenusSubOffsetY: -8
            });
        });
    </script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

app/views/application/_header_old.html.erb
<div class="col-md-9">
    <div class="row carousel-holder">
    
        <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="slide-image" src="https://s26.postimg.org/rawv65nrt/rsz_head_phone.jpg" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    
    </div>
</div>

app/views/application/_menubar.html.erb
<nav id="main-nav" role="navigation">
    <ul id="main-menu" class="sm sm-blue">
        <li><%= link_to 'Home', root_path %></li>
        <li><a href="#">Seller's Zone</a>
            <ul>
                <li><%= link_to 'Add Product', new_product_path %></li>
                <li><%= link_to 'My Products', my_products_products_path %></li>
                <li><%= link_to 'Products Sold', sold_sellers_path %></li>
            </ul>
        </li>
        <li><a href="#">Buyer's Zone</a>
            <ul>
                <li><%= link_to 'Search Products', search_buyers_path %></li>
                <li><%= link_to 'Ongoing Auctions', ongoing_auctions_buyers_path %></li>
                <li><%= link_to 'My Bids', my_bids_buyers_path %></li>
                <li><%= link_to 'Products Bought', bought_buyers_path %></li>
            </ul>
        </li>
        <li><a href="#">Admin's Zone</a>
            <ul>
                <li><%= link_to 'Add Categories', new_category_path %></li>
                <li><%= link_to 'Show Categories', categories_path %></li>
            </ul>
        </li>
        <li><a href="#">Users' Zone</a>
            <ul>
                <% if user_signed_in? %>
                  <li>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                  </li>
                <% else %>
                  <li>
                  <%= link_to('Login', new_user_session_path)  %>  
                  </li>
                <% end %>
            </ul>
        </li>
        <li><a href="#">Who are we?</a></li>
        <% if current_user %>
        <%= raw "<li style=\"float:right;\"><a href=\"#\">".html_safe %>
        <%= current_user.email %>
        <%= raw "</a></li>".html_safe %>
        <% end %>
    </ul>
</nav>

<div class="vspace"></div>

app/views/application/_sidebar.html.erb
<div class="col-md-3">
    <div class="list-group">
        <% @latest_products.each do |product| %>
            <div class="thumbnail">
                <%= link_to image_tag product.image.url(:original), :class => "product" %>
                <div class="caption">
                    <h3 class="text-center"><%= product.name %></h3>
                    <h4 class="text-center"><p class="text-info"><%= @locations[product.location_id] %></p></h4>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/application/_sold_products.html.erb
<div class="col-md-9">

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="https://placehold.it/320x150" alt="">
            <div class="caption">
                <h4 class="pull-right">$84.99</h4>
                <h4><a href="#">Fourth Product</a>
                </h4>
                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="ratings">
                <p class="pull-right">6 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                </p>
            </div>
            <%= image_tag('sold.png', style: "height: 60px") %>
        </div>
    </div>

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="https://placehold.it/320x150" alt="">
            <div class="caption">
                <h4 class="pull-right">$94.99</h4>
                <h4><a href="#">Fifth Product</a>
                </h4>
                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="ratings">
                <p class="pull-right">18 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                </p>
            </div>
            <%= image_tag('sold.png', style: "height: 60px") %>
        </div>
    </div>
    
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="https://placehold.it/320x150" alt="">
            <div class="caption">
                <h4 class="pull-right">$34.99</h4>
                <h4><a href="#">Sixth Product</a>
                </h4>
                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="ratings">
                <p class="pull-right">18 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                </p>
            </div>
            <%= image_tag('sold.png', style: "height: 60px") %>
        </div>
    </div>
    
</div>

app/views/application/about.html.erb
<div class="row">
  This online bidding system was started 2 weeks back by Dipanjan, Priyanka, Sanjana and Seemanta.
</div>

app/views/application/index.html.erb
<!-- Page Content -->
<div class="container">
    <div class="row">
        <%= render "current_products" %>
        <%= render "sold_products" %>
    </div>
</div>
<!-- /.container -->