config/routes.rb
Rails.application.routes.draw do
  
  # Application root
  root 'application#index'
  
  devise_for :users
  
  resources :products, param: :product_id do
    collection do
      get 'my_products'
      get 'bids'
    end
    member do
      post 'back'
    end
  end
  
  resources :sellers do
    collection do
      get 'bid'
      get 'sold'
      post 'start_bid'
      get 'stop_bid'
    end
  end
  
  resources :buyers do
    collection do
      get 'search'
      get 'bought'
      post 'search_products'
      get 'ongoing_auctions'
      get 'my_bids'
      get 'place_new_bid'
      post 'place_bid'
      get 'revoke_bid'
    end
  end
  
  resources :categories, param: :category_id do
    member do 
        post 'back'
    end
  end
  
  get 'bids/:bid_id', to: 'bids#show'
  post '/bids/:bid_id', to: 'bids#show'
  get 'users/searchproductsunderbid', to: 'users#search_products_under_bid', as: :search_products
  get 'buyers/productsunderbid', to: 'buyers#get_products_under_bid'
  
  resources :bids, param: :bid_id
  resources :products_under_bids, param: :product_bid_id
  
end

app/models/product.rb
class Product < ApplicationRecord
    
    belongs_to :category
    has_many :bids
    has_one :products_under_bid
    
    validates_presence_of :category
    validates :user_id, presence: true
    validates :category_id, presence: true
    validates :name, presence: true
    validates :date_added, presence: true
    has_attached_file :image, styles: { original: ["320x160#", :jpg], thumb: ["64x32#", :jpg] }, :default_url => "https://placehold.it/64x32"
    validates_attachment :image,
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
    size: { in: 0..200.kilobytes }
    self.primary_key = 'product_id'
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def my_products
    @products = Product.select("products.product_id, category_id, name, date_added, location_id, product_bid_id, sell_status").where(:user_id => current_user.id).paginate(page: params[:page], per_page: 10).joins('LEFT OUTER JOIN products_under_bids ON products.product_id = products_under_bids.product_id')
    expires_in 30.minutes, :public => true
  end
  

  def show
  end
  
  def back
    redirect_to products_url
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.date_added = Date.today

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product][:user_id] = current_user.id
      params.require(:product).permit(:user_id, :category_id, :name, :date_added, :location_id, :image)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
    def cache_key_for_products(product)
        "product/#{product.product_id}/#{product.updated_at}"
    end
    
    def cache_key_for_products_show(product)
        "product_show/#{product.product_id}/#{product.updated_at}"
    end
    
    def cache_key_for_my_bids(product)
        "my_bid/#{product.product_id}/#{product.updated_at}/#{product.maximum_bidding_price}"
    end
    
    def cache_key_for_products_table(products)
        "my_products_table/#{current_user.id}/#{products.maximum(:updated_at)}/#{products.count}"
    end
end

app/views/products/_form.html.erb
<div class="col-md-5">
    <div class="panel panel-primary">
        <div class="panel-heading"><%= action %></div>
        <div class="panel-body">

            <%= form_for(product) do |f| %>
                <% if product.errors.any? %>
                    <div id="error_explanation">
                        <h2>
                            <%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
                        <ul>
                            <% product.errors.full_messages.each do |message| %>
                                <li>
                                    <%= message %>
                                </li>
                                <% end %>
                        </ul>
                    </div>
                <% end %>

                <div class="field">
                    <%= f.label :name %>
                        <%= f.text_field :name %>
                </div>
                
                <div class="field">
                    <%= f.label :category_id %>
                        <%= f.select :category_id, categories.map { |c| [c.name, c.category_id] } %>
                </div>

                <div class="field">
                    <%= f.label :location_id %>
                    <%= f.select :location_id, @locations.each_with_index.map { |l, l_id| [l, l_id] } %>
                </div>
                
                <div class="field">
                    <%= f.label :image %>
                        <%= f.file_field :image %>
                </div>
                
                <div class="actions">
                    <%= f.submit action, class: "btn btn-success" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/products/bids.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading">Bids</div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>User</th>
            <th>Bid Amount</th>
          </tr>
        </thead>

        <% @bids=Bid.get_all_the_bids(params[:product_id]) %>
        <% if @bids != 0 %>
        <tbody>
          <% @bids.each do |bid| %>
            <tr>
              <td>
                <%= User.find(bid.user_id).email %>
              </td>
              <td>
                <%= bid.bid_amount %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <% else %>
        <tr>
          <td>No bids yet</td>
        </tr>
        <%end%>
      </table>

    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product, categories: Category.all, action: 'Edit Product' %>

app/views/products/index.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading">Products</div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>User</th>
            <th>Category</th>
            <th>Name</th>
            <th>Image</th>
            <th>Date added</th>
            <th>Location</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td>
                <%= product.user_id %>
              </td>
              <td>
                <%= Category.find(product.category_id).name %>
              </td>
              <td>
                <%= product.name %>
              </td>
              <td>
                <%= link_to image_tag product.image.url(:thumb), :class => "product" %>
              </td>
              <td>
                <%= product.date_added %>
              </td>
              <td>
                <%= @locations[product.location_id] %>
              </td>
              <td>
                <%= link_to 'Show', product %>
              </td>
              <td>
                <%= link_to 'Edit', edit_product_path(product) %>
              </td>
              <td>
                <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
              <td>
                <% if @product_bid_item = @products_under_bid.find_by_product_id_and_bid_status(product.product_id, true) %>
                <%= link_to 'Stop Bid', end_bid_sellers_path(:product_bid_id => @product_bid_item.product_bid_id) %>
                <% else %>
                <%= link_to 'Start Bid', bid_sellers_path(:product_id => product.product_id) %>
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <div id="paginate">
           <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading">Products</div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Category</th>
            <th>Date added</th>
            <th>Location</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product|%>
            <tr>
              <td>
                <%= link_to product.name, bids_products_path(:product_id => product.product_id) %>
              </td>
              <td>
                <%= Category.find(product.category_id).name %>
              </td>
              <td>
                <%= product.date_added %>
              </td>
              <td>
                <%= @locations[product.location_id] %>
              </td>
              <td>
                <%= link_to 'Show', product, :class => "btn btn-default btn-sm" %>
              </td>
              <td>
                <%= link_to 'Edit', edit_product_path(product), :class => "btn btn-default btn-sm" %>
              </td>
              <td>
                <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %>
              </td>
              <td>
                <% if product.sell_status.nil? %>
                <%= link_to 'Start Bid', bid_sellers_path(:product_id => product.product_id), :class => "btn btn-default btn-sm" %>
                <% elsif !product.sell_status %>
                <%= link_to 'Stop Bid', stop_bid_sellers_path(:product_bid_id => product.product_bid_id), :class => "btn btn-default btn-sm" %>
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <div id="paginate">
           <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form', product: @product, categories: Category.all, action: 'Add Product' %>

app/views/products/show.html.erb
<div class="col-md-5">
    <div class="panel panel-primary">
        <div class="panel-heading">View Product</div>
        <div class="panel-body">
          
          <div class="field">
              <p id="notice"><%= notice %>
          </div>
          
          <% cache(cache_key_for_products_show(@product)) do %>
          <div class="field">
              <p>
                <strong>Product:</strong>
                <%= @product.name %>
              </p>
          </div>
          
          <div class="field">
              <p>
                <strong>User:</strong>
                <%= @product.user_id %>
              </p>
          </div>
          
          <div class="field">
              <p>
                <strong>Category:</strong>
                <%= @product.category_id %>
              </p>
          </div>
          
          <div class="field">
              <p>
                <strong>Date added:</strong>
                <%= @product.date_added %>
              </p>
          </div>
          
          <div class="field">
              <p>
                <strong>Location:</strong>
                <%= @locations[@product.location_id] %>
              </p>
          </div>
          <div class="field">
            <%= link_to image_tag @product.image.url(:original) %>
          </div>
          
          <%= form_for( @product, :url => my_products_products_path( @product ), :html => { :method => :get } ) do |f| %>
              <div class="actions">
                  <p> <%= f.submit 'Back', class: "btn btn-success" %> </p>
              </div>
          <% end %>
          <% end %>      
        </div>
    </div>
</div>